export const SET_RECORDING = 'SET_RECORDING'
export const SET_TAGREADPULSE = 'SET_TAGREADPULSE'
export const SET_TAGS = 'SET_TAGS'
export const POST_TAG = 'POST_TAG'
export const DELETE_TAG = 'DELETE_TAG'
export const PUT_TAG = 'PUT_TAG'
